### PR TITLE
Impliment standard Icon sizes

### PR DESCRIPTION
**Pull request by rav3n11**

### CODE REVIEW

**Comment by rav3n11** [comment]
So @Fidesnoella The way the component overrides work is that they override the small and large fontSizes for the icons. So when you want an icon to be large, all you have to pass is the fontSize="large" prop and the override will take our styles for it.

```typescript
<SettingsIcon fontSize="large" data-testid={DATA_TEST_ID.APP_HEADER_ICON_SETTINGS} />
```

**Comment by rav3n11** [comment]
@Fidesnoella Would be nice if we could show off these styles in the storybook under styles? Could you add that?

**Comment by rav3n11** [comment]
Also @Fidesnoella We should go through all the files and find icons that are not setting their sizes this way. For example the sidebar icons...

**Comment by ApostolosBenisis** [comment]
@Fidesnoella when starting work on a new task you should fetch the latest main and create a new branch from that.
Your branch is old and you now have to merge the changes... this is extra work without any reason.

**Review by rav3n11 — COMMENTED** [review]
LGTM

**Pull request merged**
